# Generated by Django 4.2.3 on 2023-08-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("pw", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=10)),
                ("game_score", models.IntegerField(default=0)),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("main_category", models.CharField(max_length=15)),
                ("sub_category", models.CharField(max_length=15)),
                ("level", models.IntegerField()),
                ("length", models.IntegerField()),
                ("description", models.TextField()),
                ("json", models.ManyToManyField(to="handi.mediaentry")),
            ],
        ),
    ]
