# Generated by Django 4.2.4 on 2023-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.TextField(default='<svg viewBox="0 0 36 36" fill="none" role="img" xmlns="http://www.w3.org/2000/svg" width="80" height="80"><mask id="mask__beam" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36"><rect width="36" height="36" fill="#FFFFFF"></rect></mask><g mask="url(#mask__beam)"><rect width="36" height="36" fill="#92A1C6"></rect><rect x="0" y="0" width="36" height="36" transform="translate(-3 -3) rotate(167 18 18) scale(1.2)" fill="#F0AB3D" rx="36"></rect><g transform="translate(-7 0) rotate(7 18 18)"><path d="M15 21c2 1 4 1 6 0" stroke="#000000" fill="none" stroke-linecap="round"></path><rect x="12" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#000000"></rect><rect x="22" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#000000"></rect></g></g></svg>'),
        ),
    ]
