# Generated by Django 4.2.3 on 2023-08-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.TextField(
                default='<svg viewBox="0 0 36 36" fill="none" role="img" xmlns="http://www.w3.org/2000/svg" width="80" height="80"><mask id="mask__beam" maskUnits="userSpaceOnUse" x="0" y="0" width="36" height="36"><rect width="36" height="36" fill="#FFFFFF"></rect></mask><g mask="url(#mask__beam)"><rect width="36" height="36" fill="#92A1C6"></rect><rect x="0" y="0" width="36" height="36" transform="translate(6 6) rotate(312 18 18) scale(1)" fill="#F0AB3D" rx="6"></rect><g transform="translate(0 5) rotate(-2 18 18)"><path d="M13,19 a1,0.75 0 0,0 10,0" fill="#000000"></path><rect x="12" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#000000"></rect><rect x="22" y="14" width="1.5" height="2" rx="1" stroke="none" fill="#000000"></rect></g></g></svg>'
            ),
        ),
    ]
