# Generated by Django 4.2.3 on 2023-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handi", "0002_lecturemanager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lecture",
            old_name="json",
            new_name="media_entry",
        ),
        migrations.RenameField(
            model_name="mediaentry",
            old_name="json",
            new_name="media_entry",
        ),
        migrations.AddField(
            model_name="lecture",
            name="theme_category",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
