# Generated by Django 4.2.3 on 2023-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handi", "0003_rename_json_lecture_media_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="lecture_img",
            field=models.ImageField(blank=True, null=True, upload_to="lecture/"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
