# Generated by Django 4.2.3 on 2023-08-02 07:50

from django.db import migrations, models
import handi.models


class Migration(migrations.Migration):

    dependencies = [
        ('handi', '0004_lecture_lecture_img_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=handi.models.renameImagePath),
        ),
    ]
