# Generated by Django 4.2.3 on 2023-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handi', '0005_lecture_name_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturemanager',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
