# Generated by Django 4.2.3 on 2023-08-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handi', '0006_lecturemanager_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturemanager',
            name='tt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
