# Generated by Django 4.2.3 on 2023-08-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handi', '0007_lecturemanager_tt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturemanager',
            name='tt',
        ),
    ]
